// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: zrchain/treasury/key.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { WalletType, walletTypeFromJSON, walletTypeToJSON } from "./wallet";

export const protobufPackage = "zrchain.treasury";

/**
 * KeyRequestStatus indicates the status of a key request.
 * A request starts as "pending", waiting to be picked up. Then it can move to
 * either "approved" or "rejected", depending on the decision of the MPC nodes.
 */
export enum KeyRequestStatus {
  /** KEY_REQUEST_STATUS_UNSPECIFIED - The request is missing the status field. */
  KEY_REQUEST_STATUS_UNSPECIFIED = 0,
  /**
   * KEY_REQUEST_STATUS_PENDING - The request is waiting to be fulfilled. This is the initial state of a
   * request.
   */
  KEY_REQUEST_STATUS_PENDING = 1,
  /**
   * KEY_REQUEST_STATUS_PARTIAL - The request is partially fulfilled - at least one more response from
   * a different MPC party is needed to confirm it.
   */
  KEY_REQUEST_STATUS_PARTIAL = 2,
  /** KEY_REQUEST_STATUS_FULFILLED - The request was fulfilled. This is a final state for a request. */
  KEY_REQUEST_STATUS_FULFILLED = 3,
  /** KEY_REQUEST_STATUS_REJECTED - The request was rejected. This is a final state for a request. */
  KEY_REQUEST_STATUS_REJECTED = 4,
  UNRECOGNIZED = -1,
}

export function keyRequestStatusFromJSON(object: any): KeyRequestStatus {
  switch (object) {
    case 0:
    case "KEY_REQUEST_STATUS_UNSPECIFIED":
      return KeyRequestStatus.KEY_REQUEST_STATUS_UNSPECIFIED;
    case 1:
    case "KEY_REQUEST_STATUS_PENDING":
      return KeyRequestStatus.KEY_REQUEST_STATUS_PENDING;
    case 2:
    case "KEY_REQUEST_STATUS_PARTIAL":
      return KeyRequestStatus.KEY_REQUEST_STATUS_PARTIAL;
    case 3:
    case "KEY_REQUEST_STATUS_FULFILLED":
      return KeyRequestStatus.KEY_REQUEST_STATUS_FULFILLED;
    case 4:
    case "KEY_REQUEST_STATUS_REJECTED":
      return KeyRequestStatus.KEY_REQUEST_STATUS_REJECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return KeyRequestStatus.UNRECOGNIZED;
  }
}

export function keyRequestStatusToJSON(object: KeyRequestStatus): string {
  switch (object) {
    case KeyRequestStatus.KEY_REQUEST_STATUS_UNSPECIFIED:
      return "KEY_REQUEST_STATUS_UNSPECIFIED";
    case KeyRequestStatus.KEY_REQUEST_STATUS_PENDING:
      return "KEY_REQUEST_STATUS_PENDING";
    case KeyRequestStatus.KEY_REQUEST_STATUS_PARTIAL:
      return "KEY_REQUEST_STATUS_PARTIAL";
    case KeyRequestStatus.KEY_REQUEST_STATUS_FULFILLED:
      return "KEY_REQUEST_STATUS_FULFILLED";
    case KeyRequestStatus.KEY_REQUEST_STATUS_REJECTED:
      return "KEY_REQUEST_STATUS_REJECTED";
    case KeyRequestStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * KeyType indicates what crypto key algo will be used by this key (e.g. ECDSA
 * with secp256k1 curve). Its public key will be one of the specified type.
 */
export enum KeyType {
  /** KEY_TYPE_UNSPECIFIED - The key type is missing. */
  KEY_TYPE_UNSPECIFIED = 0,
  /** KEY_TYPE_ECDSA_SECP256K1 - The key is an ECDSA secp256k1 key. */
  KEY_TYPE_ECDSA_SECP256K1 = 1,
  /** KEY_TYPE_EDDSA_ED25519 - The key is an EdDSA Ed25519 key. */
  KEY_TYPE_EDDSA_ED25519 = 2,
  /** KEY_TYPE_BITCOIN_SECP256K1 - Standard Bitcoin Keys */
  KEY_TYPE_BITCOIN_SECP256K1 = 3,
  UNRECOGNIZED = -1,
}

export function keyTypeFromJSON(object: any): KeyType {
  switch (object) {
    case 0:
    case "KEY_TYPE_UNSPECIFIED":
      return KeyType.KEY_TYPE_UNSPECIFIED;
    case 1:
    case "KEY_TYPE_ECDSA_SECP256K1":
      return KeyType.KEY_TYPE_ECDSA_SECP256K1;
    case 2:
    case "KEY_TYPE_EDDSA_ED25519":
      return KeyType.KEY_TYPE_EDDSA_ED25519;
    case 3:
    case "KEY_TYPE_BITCOIN_SECP256K1":
      return KeyType.KEY_TYPE_BITCOIN_SECP256K1;
    case -1:
    case "UNRECOGNIZED":
    default:
      return KeyType.UNRECOGNIZED;
  }
}

export function keyTypeToJSON(object: KeyType): string {
  switch (object) {
    case KeyType.KEY_TYPE_UNSPECIFIED:
      return "KEY_TYPE_UNSPECIFIED";
    case KeyType.KEY_TYPE_ECDSA_SECP256K1:
      return "KEY_TYPE_ECDSA_SECP256K1";
    case KeyType.KEY_TYPE_EDDSA_ED25519:
      return "KEY_TYPE_EDDSA_ED25519";
    case KeyType.KEY_TYPE_BITCOIN_SECP256K1:
      return "KEY_TYPE_BITCOIN_SECP256K1";
    case KeyType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** format of a key request */
export interface KeyRequest {
  id: number;
  creator: string;
  workspaceAddr: string;
  keyringAddr: string;
  keyType: KeyType;
  status: KeyRequestStatus;
  keyringPartySignatures: Uint8Array[];
  rejectReason: string;
  index: number;
  signPolicyId: number;
  /** Optional */
  zenbtcMetadata: ZenBTCMetdata | undefined;
}

/** format of a key request response */
export interface KeyReqResponse {
  id: number;
  creator: string;
  workspaceAddr: string;
  keyringAddr: string;
  keyType: string;
  status: string;
  keyringPartySignatures: Uint8Array[];
  rejectReason: string;
  index: number;
  signPolicyId: number;
  /** Optional */
  zenbtcMetadata: ZenBTCMetdata | undefined;
}

/** format of a key */
export interface Key {
  id: number;
  workspaceAddr: string;
  keyringAddr: string;
  type: KeyType;
  publicKey: Uint8Array;
  index: number;
  signPolicyId: number;
  /** Optional */
  zenbtcMetadata: ZenBTCMetdata | undefined;
}

/** format of a key response */
export interface KeyResponse {
  id: number;
  workspaceAddr: string;
  keyringAddr: string;
  type: string;
  publicKey: Uint8Array;
  index: number;
  signPolicyId: number;
  /** Optional */
  zenbtcMetadata: ZenBTCMetdata | undefined;
}

/** ZenBTCMetdata is the metadata for a key on the zenBTC keyring. */
export interface ZenBTCMetdata {
  /** Optional */
  recipientAddr: string;
  /** Optional */
  chainType: WalletType;
  /** Optional */
  chainId: number;
  /** Optional */
  returnAddress: string;
}

/** PendingMintTransaction is the metadata for a pending zenBTC mint transaction. */
export interface PendingMintTransaction {
  chainId: number;
  chainType: WalletType;
  recipientAddress: string;
  amount: number;
  creator: string;
  keyId: number;
}

export interface PendingMintTransactions {
  txs: PendingMintTransaction[];
}

function createBaseKeyRequest(): KeyRequest {
  return {
    id: 0,
    creator: "",
    workspaceAddr: "",
    keyringAddr: "",
    keyType: 0,
    status: 0,
    keyringPartySignatures: [],
    rejectReason: "",
    index: 0,
    signPolicyId: 0,
    zenbtcMetadata: undefined,
  };
}

export const KeyRequest: MessageFns<KeyRequest> = {
  encode(message: KeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    if (message.workspaceAddr !== "") {
      writer.uint32(26).string(message.workspaceAddr);
    }
    if (message.keyringAddr !== "") {
      writer.uint32(34).string(message.keyringAddr);
    }
    if (message.keyType !== 0) {
      writer.uint32(40).int32(message.keyType);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    for (const v of message.keyringPartySignatures) {
      writer.uint32(58).bytes(v!);
    }
    if (message.rejectReason !== "") {
      writer.uint32(66).string(message.rejectReason);
    }
    if (message.index !== 0) {
      writer.uint32(72).uint64(message.index);
    }
    if (message.signPolicyId !== 0) {
      writer.uint32(80).uint64(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      ZenBTCMetdata.encode(message.zenbtcMetadata, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.workspaceAddr = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.keyringAddr = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.keyType = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.keyringPartySignatures.push(reader.bytes());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.rejectReason = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.index = longToNumber(reader.uint64());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.signPolicyId = longToNumber(reader.uint64());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.zenbtcMetadata = ZenBTCMetdata.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      workspaceAddr: isSet(object.workspaceAddr) ? globalThis.String(object.workspaceAddr) : "",
      keyringAddr: isSet(object.keyringAddr) ? globalThis.String(object.keyringAddr) : "",
      keyType: isSet(object.keyType) ? keyTypeFromJSON(object.keyType) : 0,
      status: isSet(object.status) ? keyRequestStatusFromJSON(object.status) : 0,
      keyringPartySignatures: globalThis.Array.isArray(object?.keyringPartySignatures)
        ? object.keyringPartySignatures.map((e: any) => bytesFromBase64(e))
        : [],
      rejectReason: isSet(object.rejectReason) ? globalThis.String(object.rejectReason) : "",
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      signPolicyId: isSet(object.signPolicyId) ? globalThis.Number(object.signPolicyId) : 0,
      zenbtcMetadata: isSet(object.zenbtcMetadata) ? ZenBTCMetdata.fromJSON(object.zenbtcMetadata) : undefined,
    };
  },

  toJSON(message: KeyRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.workspaceAddr !== "") {
      obj.workspaceAddr = message.workspaceAddr;
    }
    if (message.keyringAddr !== "") {
      obj.keyringAddr = message.keyringAddr;
    }
    if (message.keyType !== 0) {
      obj.keyType = keyTypeToJSON(message.keyType);
    }
    if (message.status !== 0) {
      obj.status = keyRequestStatusToJSON(message.status);
    }
    if (message.keyringPartySignatures?.length) {
      obj.keyringPartySignatures = message.keyringPartySignatures.map((e) => base64FromBytes(e));
    }
    if (message.rejectReason !== "") {
      obj.rejectReason = message.rejectReason;
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.signPolicyId !== 0) {
      obj.signPolicyId = Math.round(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      obj.zenbtcMetadata = ZenBTCMetdata.toJSON(message.zenbtcMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyRequest>, I>>(base?: I): KeyRequest {
    return KeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyRequest>, I>>(object: I): KeyRequest {
    const message = createBaseKeyRequest();
    message.id = object.id ?? 0;
    message.creator = object.creator ?? "";
    message.workspaceAddr = object.workspaceAddr ?? "";
    message.keyringAddr = object.keyringAddr ?? "";
    message.keyType = object.keyType ?? 0;
    message.status = object.status ?? 0;
    message.keyringPartySignatures = object.keyringPartySignatures?.map((e) => e) || [];
    message.rejectReason = object.rejectReason ?? "";
    message.index = object.index ?? 0;
    message.signPolicyId = object.signPolicyId ?? 0;
    message.zenbtcMetadata = (object.zenbtcMetadata !== undefined && object.zenbtcMetadata !== null)
      ? ZenBTCMetdata.fromPartial(object.zenbtcMetadata)
      : undefined;
    return message;
  },
};

function createBaseKeyReqResponse(): KeyReqResponse {
  return {
    id: 0,
    creator: "",
    workspaceAddr: "",
    keyringAddr: "",
    keyType: "",
    status: "",
    keyringPartySignatures: [],
    rejectReason: "",
    index: 0,
    signPolicyId: 0,
    zenbtcMetadata: undefined,
  };
}

export const KeyReqResponse: MessageFns<KeyReqResponse> = {
  encode(message: KeyReqResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.creator !== "") {
      writer.uint32(18).string(message.creator);
    }
    if (message.workspaceAddr !== "") {
      writer.uint32(26).string(message.workspaceAddr);
    }
    if (message.keyringAddr !== "") {
      writer.uint32(34).string(message.keyringAddr);
    }
    if (message.keyType !== "") {
      writer.uint32(42).string(message.keyType);
    }
    if (message.status !== "") {
      writer.uint32(50).string(message.status);
    }
    for (const v of message.keyringPartySignatures) {
      writer.uint32(58).bytes(v!);
    }
    if (message.rejectReason !== "") {
      writer.uint32(66).string(message.rejectReason);
    }
    if (message.index !== 0) {
      writer.uint32(72).uint64(message.index);
    }
    if (message.signPolicyId !== 0) {
      writer.uint32(80).uint64(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      ZenBTCMetdata.encode(message.zenbtcMetadata, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyReqResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyReqResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.workspaceAddr = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.keyringAddr = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.keyType = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.status = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.keyringPartySignatures.push(reader.bytes());
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.rejectReason = reader.string();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.index = longToNumber(reader.uint64());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.signPolicyId = longToNumber(reader.uint64());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.zenbtcMetadata = ZenBTCMetdata.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyReqResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      workspaceAddr: isSet(object.workspaceAddr) ? globalThis.String(object.workspaceAddr) : "",
      keyringAddr: isSet(object.keyringAddr) ? globalThis.String(object.keyringAddr) : "",
      keyType: isSet(object.keyType) ? globalThis.String(object.keyType) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      keyringPartySignatures: globalThis.Array.isArray(object?.keyringPartySignatures)
        ? object.keyringPartySignatures.map((e: any) => bytesFromBase64(e))
        : [],
      rejectReason: isSet(object.rejectReason) ? globalThis.String(object.rejectReason) : "",
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      signPolicyId: isSet(object.signPolicyId) ? globalThis.Number(object.signPolicyId) : 0,
      zenbtcMetadata: isSet(object.zenbtcMetadata) ? ZenBTCMetdata.fromJSON(object.zenbtcMetadata) : undefined,
    };
  },

  toJSON(message: KeyReqResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.workspaceAddr !== "") {
      obj.workspaceAddr = message.workspaceAddr;
    }
    if (message.keyringAddr !== "") {
      obj.keyringAddr = message.keyringAddr;
    }
    if (message.keyType !== "") {
      obj.keyType = message.keyType;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.keyringPartySignatures?.length) {
      obj.keyringPartySignatures = message.keyringPartySignatures.map((e) => base64FromBytes(e));
    }
    if (message.rejectReason !== "") {
      obj.rejectReason = message.rejectReason;
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.signPolicyId !== 0) {
      obj.signPolicyId = Math.round(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      obj.zenbtcMetadata = ZenBTCMetdata.toJSON(message.zenbtcMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyReqResponse>, I>>(base?: I): KeyReqResponse {
    return KeyReqResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyReqResponse>, I>>(object: I): KeyReqResponse {
    const message = createBaseKeyReqResponse();
    message.id = object.id ?? 0;
    message.creator = object.creator ?? "";
    message.workspaceAddr = object.workspaceAddr ?? "";
    message.keyringAddr = object.keyringAddr ?? "";
    message.keyType = object.keyType ?? "";
    message.status = object.status ?? "";
    message.keyringPartySignatures = object.keyringPartySignatures?.map((e) => e) || [];
    message.rejectReason = object.rejectReason ?? "";
    message.index = object.index ?? 0;
    message.signPolicyId = object.signPolicyId ?? 0;
    message.zenbtcMetadata = (object.zenbtcMetadata !== undefined && object.zenbtcMetadata !== null)
      ? ZenBTCMetdata.fromPartial(object.zenbtcMetadata)
      : undefined;
    return message;
  },
};

function createBaseKey(): Key {
  return {
    id: 0,
    workspaceAddr: "",
    keyringAddr: "",
    type: 0,
    publicKey: new Uint8Array(0),
    index: 0,
    signPolicyId: 0,
    zenbtcMetadata: undefined,
  };
}

export const Key: MessageFns<Key> = {
  encode(message: Key, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.workspaceAddr !== "") {
      writer.uint32(18).string(message.workspaceAddr);
    }
    if (message.keyringAddr !== "") {
      writer.uint32(26).string(message.keyringAddr);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.publicKey.length !== 0) {
      writer.uint32(42).bytes(message.publicKey);
    }
    if (message.index !== 0) {
      writer.uint32(72).uint64(message.index);
    }
    if (message.signPolicyId !== 0) {
      writer.uint32(80).uint64(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      ZenBTCMetdata.encode(message.zenbtcMetadata, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Key {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.workspaceAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.keyringAddr = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.index = longToNumber(reader.uint64());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.signPolicyId = longToNumber(reader.uint64());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.zenbtcMetadata = ZenBTCMetdata.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Key {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      workspaceAddr: isSet(object.workspaceAddr) ? globalThis.String(object.workspaceAddr) : "",
      keyringAddr: isSet(object.keyringAddr) ? globalThis.String(object.keyringAddr) : "",
      type: isSet(object.type) ? keyTypeFromJSON(object.type) : 0,
      publicKey: isSet(object.publicKey) ? bytesFromBase64(object.publicKey) : new Uint8Array(0),
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      signPolicyId: isSet(object.signPolicyId) ? globalThis.Number(object.signPolicyId) : 0,
      zenbtcMetadata: isSet(object.zenbtcMetadata) ? ZenBTCMetdata.fromJSON(object.zenbtcMetadata) : undefined,
    };
  },

  toJSON(message: Key): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.workspaceAddr !== "") {
      obj.workspaceAddr = message.workspaceAddr;
    }
    if (message.keyringAddr !== "") {
      obj.keyringAddr = message.keyringAddr;
    }
    if (message.type !== 0) {
      obj.type = keyTypeToJSON(message.type);
    }
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.signPolicyId !== 0) {
      obj.signPolicyId = Math.round(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      obj.zenbtcMetadata = ZenBTCMetdata.toJSON(message.zenbtcMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Key>, I>>(base?: I): Key {
    return Key.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Key>, I>>(object: I): Key {
    const message = createBaseKey();
    message.id = object.id ?? 0;
    message.workspaceAddr = object.workspaceAddr ?? "";
    message.keyringAddr = object.keyringAddr ?? "";
    message.type = object.type ?? 0;
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.index = object.index ?? 0;
    message.signPolicyId = object.signPolicyId ?? 0;
    message.zenbtcMetadata = (object.zenbtcMetadata !== undefined && object.zenbtcMetadata !== null)
      ? ZenBTCMetdata.fromPartial(object.zenbtcMetadata)
      : undefined;
    return message;
  },
};

function createBaseKeyResponse(): KeyResponse {
  return {
    id: 0,
    workspaceAddr: "",
    keyringAddr: "",
    type: "",
    publicKey: new Uint8Array(0),
    index: 0,
    signPolicyId: 0,
    zenbtcMetadata: undefined,
  };
}

export const KeyResponse: MessageFns<KeyResponse> = {
  encode(message: KeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.workspaceAddr !== "") {
      writer.uint32(18).string(message.workspaceAddr);
    }
    if (message.keyringAddr !== "") {
      writer.uint32(26).string(message.keyringAddr);
    }
    if (message.type !== "") {
      writer.uint32(34).string(message.type);
    }
    if (message.publicKey.length !== 0) {
      writer.uint32(42).bytes(message.publicKey);
    }
    if (message.index !== 0) {
      writer.uint32(72).uint64(message.index);
    }
    if (message.signPolicyId !== 0) {
      writer.uint32(80).uint64(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      ZenBTCMetdata.encode(message.zenbtcMetadata, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.workspaceAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.keyringAddr = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.type = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.index = longToNumber(reader.uint64());
          continue;
        case 10:
          if (tag !== 80) {
            break;
          }

          message.signPolicyId = longToNumber(reader.uint64());
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.zenbtcMetadata = ZenBTCMetdata.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyResponse {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      workspaceAddr: isSet(object.workspaceAddr) ? globalThis.String(object.workspaceAddr) : "",
      keyringAddr: isSet(object.keyringAddr) ? globalThis.String(object.keyringAddr) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      publicKey: isSet(object.publicKey) ? bytesFromBase64(object.publicKey) : new Uint8Array(0),
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      signPolicyId: isSet(object.signPolicyId) ? globalThis.Number(object.signPolicyId) : 0,
      zenbtcMetadata: isSet(object.zenbtcMetadata) ? ZenBTCMetdata.fromJSON(object.zenbtcMetadata) : undefined,
    };
  },

  toJSON(message: KeyResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.workspaceAddr !== "") {
      obj.workspaceAddr = message.workspaceAddr;
    }
    if (message.keyringAddr !== "") {
      obj.keyringAddr = message.keyringAddr;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.signPolicyId !== 0) {
      obj.signPolicyId = Math.round(message.signPolicyId);
    }
    if (message.zenbtcMetadata !== undefined) {
      obj.zenbtcMetadata = ZenBTCMetdata.toJSON(message.zenbtcMetadata);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyResponse>, I>>(base?: I): KeyResponse {
    return KeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyResponse>, I>>(object: I): KeyResponse {
    const message = createBaseKeyResponse();
    message.id = object.id ?? 0;
    message.workspaceAddr = object.workspaceAddr ?? "";
    message.keyringAddr = object.keyringAddr ?? "";
    message.type = object.type ?? "";
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.index = object.index ?? 0;
    message.signPolicyId = object.signPolicyId ?? 0;
    message.zenbtcMetadata = (object.zenbtcMetadata !== undefined && object.zenbtcMetadata !== null)
      ? ZenBTCMetdata.fromPartial(object.zenbtcMetadata)
      : undefined;
    return message;
  },
};

function createBaseZenBTCMetdata(): ZenBTCMetdata {
  return { recipientAddr: "", chainType: 0, chainId: 0, returnAddress: "" };
}

export const ZenBTCMetdata: MessageFns<ZenBTCMetdata> = {
  encode(message: ZenBTCMetdata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.recipientAddr !== "") {
      writer.uint32(10).string(message.recipientAddr);
    }
    if (message.chainType !== 0) {
      writer.uint32(16).int32(message.chainType);
    }
    if (message.chainId !== 0) {
      writer.uint32(24).uint64(message.chainId);
    }
    if (message.returnAddress !== "") {
      writer.uint32(34).string(message.returnAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ZenBTCMetdata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseZenBTCMetdata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.recipientAddr = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.chainType = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.chainId = longToNumber(reader.uint64());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.returnAddress = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ZenBTCMetdata {
    return {
      recipientAddr: isSet(object.recipientAddr) ? globalThis.String(object.recipientAddr) : "",
      chainType: isSet(object.chainType) ? walletTypeFromJSON(object.chainType) : 0,
      chainId: isSet(object.chainId) ? globalThis.Number(object.chainId) : 0,
      returnAddress: isSet(object.returnAddress) ? globalThis.String(object.returnAddress) : "",
    };
  },

  toJSON(message: ZenBTCMetdata): unknown {
    const obj: any = {};
    if (message.recipientAddr !== "") {
      obj.recipientAddr = message.recipientAddr;
    }
    if (message.chainType !== 0) {
      obj.chainType = walletTypeToJSON(message.chainType);
    }
    if (message.chainId !== 0) {
      obj.chainId = Math.round(message.chainId);
    }
    if (message.returnAddress !== "") {
      obj.returnAddress = message.returnAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ZenBTCMetdata>, I>>(base?: I): ZenBTCMetdata {
    return ZenBTCMetdata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ZenBTCMetdata>, I>>(object: I): ZenBTCMetdata {
    const message = createBaseZenBTCMetdata();
    message.recipientAddr = object.recipientAddr ?? "";
    message.chainType = object.chainType ?? 0;
    message.chainId = object.chainId ?? 0;
    message.returnAddress = object.returnAddress ?? "";
    return message;
  },
};

function createBasePendingMintTransaction(): PendingMintTransaction {
  return { chainId: 0, chainType: 0, recipientAddress: "", amount: 0, creator: "", keyId: 0 };
}

export const PendingMintTransaction: MessageFns<PendingMintTransaction> = {
  encode(message: PendingMintTransaction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainId !== 0) {
      writer.uint32(8).uint64(message.chainId);
    }
    if (message.chainType !== 0) {
      writer.uint32(16).int32(message.chainType);
    }
    if (message.recipientAddress !== "") {
      writer.uint32(26).string(message.recipientAddress);
    }
    if (message.amount !== 0) {
      writer.uint32(32).uint64(message.amount);
    }
    if (message.creator !== "") {
      writer.uint32(42).string(message.creator);
    }
    if (message.keyId !== 0) {
      writer.uint32(48).uint64(message.keyId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PendingMintTransaction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePendingMintTransaction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.chainId = longToNumber(reader.uint64());
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.chainType = reader.int32() as any;
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.recipientAddress = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.amount = longToNumber(reader.uint64());
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.creator = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.keyId = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PendingMintTransaction {
    return {
      chainId: isSet(object.chainId) ? globalThis.Number(object.chainId) : 0,
      chainType: isSet(object.chainType) ? walletTypeFromJSON(object.chainType) : 0,
      recipientAddress: isSet(object.recipientAddress) ? globalThis.String(object.recipientAddress) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      keyId: isSet(object.keyId) ? globalThis.Number(object.keyId) : 0,
    };
  },

  toJSON(message: PendingMintTransaction): unknown {
    const obj: any = {};
    if (message.chainId !== 0) {
      obj.chainId = Math.round(message.chainId);
    }
    if (message.chainType !== 0) {
      obj.chainType = walletTypeToJSON(message.chainType);
    }
    if (message.recipientAddress !== "") {
      obj.recipientAddress = message.recipientAddress;
    }
    if (message.amount !== 0) {
      obj.amount = Math.round(message.amount);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.keyId !== 0) {
      obj.keyId = Math.round(message.keyId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PendingMintTransaction>, I>>(base?: I): PendingMintTransaction {
    return PendingMintTransaction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PendingMintTransaction>, I>>(object: I): PendingMintTransaction {
    const message = createBasePendingMintTransaction();
    message.chainId = object.chainId ?? 0;
    message.chainType = object.chainType ?? 0;
    message.recipientAddress = object.recipientAddress ?? "";
    message.amount = object.amount ?? 0;
    message.creator = object.creator ?? "";
    message.keyId = object.keyId ?? 0;
    return message;
  },
};

function createBasePendingMintTransactions(): PendingMintTransactions {
  return { txs: [] };
}

export const PendingMintTransactions: MessageFns<PendingMintTransactions> = {
  encode(message: PendingMintTransactions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.txs) {
      PendingMintTransaction.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PendingMintTransactions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePendingMintTransactions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.txs.push(PendingMintTransaction.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PendingMintTransactions {
    return {
      txs: globalThis.Array.isArray(object?.txs) ? object.txs.map((e: any) => PendingMintTransaction.fromJSON(e)) : [],
    };
  },

  toJSON(message: PendingMintTransactions): unknown {
    const obj: any = {};
    if (message.txs?.length) {
      obj.txs = message.txs.map((e) => PendingMintTransaction.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PendingMintTransactions>, I>>(base?: I): PendingMintTransactions {
    return PendingMintTransactions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PendingMintTransactions>, I>>(object: I): PendingMintTransactions {
    const message = createBasePendingMintTransactions();
    message.txs = object.txs?.map((e) => PendingMintTransaction.fromPartial(e)) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
